Refactoring: Replace hard-coded runWithPrompt command-line argument parse with delegation
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/ensurePrompting b/bin/ensurePrompting
--- a/bin/ensurePrompting
+++ b/bin/ensurePrompting
@@ -102,12 +102,6 @@ do
 	--prompt-command|-P)
 			shift; promptCommands+="${promptCommands:+ $ENSUREPROMPTING_COMMAND_JOINER }$1"; shift;;
 	--bare)		shift; isBare=t; runWithCommand=runWith;;
-	--exit-on-failure)
-			bashArgs+=(-e); runWithPromptArgs+=("$1"); shift;;
-	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--emulate-prompt|--worst-status|--status-99-is-noop)
-			runWithPromptArgs+=("$1"); shift;;
-	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
 	--keep-prompt|-k)
 			userpromptArgs+=("$1"); shift;;
 	--timeout|--for|-t)
@@ -115,8 +109,21 @@ do
 	--no-prompt)	shift; userpromptCommand=:;;
 	--prompt|-p)	shift; userpromptPrompt=(-- "${1?}"); shift;;
 	--id|-i)	shift; id="${1:?}"; shift;;
+
+	--exit-on-failure)
+			bashArgs+=(-e); runWithPromptArgs+=("$1"); shift;;
 	--)		shift; break;;
-	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
+	-*)		if argCount=$(runWithPrompt --understands "$@"); then
+			    while ((argCount-- > 0))
+			    do
+				runWithPromptArgs+=("$1"); shift
+			    done
+			elif [ $? -eq 2 ]; then
+			    exit 2
+			else
+			    { echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2
+			fi
+			;;
 	*)		break;;
     esac
 done
