runAll: FIX: Actually use runWith if any runWithPrompt args are given (cp. inkarkat/shell-tools@c3b95ab)
The default $runWithCommand never saw action because $with is only changed by --with-prompt. Do away with a separate $runWithCommand and use $with for the selection as well.
Robustness: Handle with=header via fall-through and assert on unknown $what values.

(This relates to commit inkarkat/shell-tools@c3b95abe6d20db779acd5fd6077993880cc6b5b0)

diff --git a/bin/runAll b/bin/runAll
--- a/bin/runAll
+++ b/bin/runAll
@@ -46,7 +46,6 @@ HELPTEXT
 
 with=
 typeset -a commands=()
-runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -54,12 +53,12 @@ do
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--command|-c)	shift; commands+=("$1"); shift;;
 	--with-header)	shift; with=header;;
-	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
+	--with-prompt)	shift; with=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
-			runWithPromptArgs+=("$1"); shift;;
+			runWithPromptArgs+=("$1"); shift; : ${with:=runWith};;
 	--initial-status|--no-count-on|--exit-on|--exit-unless|--comment|--summarize-failed|--summarize-failed-separator)
-			runWithPromptArgs+=("$1" "$2"); shift; shift;;
+			runWithPromptArgs+=("$1" "$2"); shift; shift; : ${with:=runWith};;
 
 	--)		shift; break;;
 	-*)		{ echo "ERROR: Unknown option \"$1\"!"; echo; printUsage "$0"; } >&2; exit 2;;
@@ -80,16 +79,17 @@ if [ ${#commands[@]} -eq 0 ]; then
     echo
     printUsage "$0"
     exit 2
-elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = 'header' ]; then
     echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
     echo
     printUsage "$0"
     exit 2
 fi >&2
 
-
+isFirst=t
+isHeader=
 case "$with" in
-    prompt)
+    runWith*)
 	[ ${#runWithPromptArgs[@]} -eq 0 ] && runWithPromptArgs=(--worst-status)
 	for c in "${commands[@]}"
 	do
@@ -101,24 +101,24 @@ case "$with" in
 		printf ' %q' "$@"
 		printf '\n'
 	    fi
-	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
+	done | ${with:?} "${runWithPromptArgs[@]}"
 	;;
-    *)
+    header)
+	isHeader=t;&
+    '')
 	status=0
-	typeset -a firstArg=(--first)
 	for c in "${commands[@]}"
 	do
-	    if [ "$with" = 'header' ]; then
-		header "${firstArg[@]}" "$c"
-		firstArg=()
-	    fi
+	    [ ! "$isHeader" ] || header ${isFirst:+--first} "$c"
 
 	    printf -v quotedArgs '%q ' "$@"; quotedArgs="${quotedArgs% }"
 	    typeset -a a=("$@")
 	    interpolatedCommand="${c//"$argMarker"/$quotedArgs}"
 	    [ "$interpolatedCommand" = "$c" ] || a=()
 	    eval "$interpolatedCommand" '"${a[@]}"' || { exitStatus=$?; if [ $exitStatus -gt $status ]; then status=$exitStatus; fi; }
+	    isFirst=
 	done
 	exit $status
 	;;
+    *)	printf >&2 'ASSERT: Invalid strategy: %s\n' "$with"; exit 3;;
 esac
