runAll: ENH: Also support runWith arguments without --with-prompt

diff --git a/bin/runAll b/bin/runAll
--- a/bin/runAll
+++ b/bin/runAll
@@ -7,7 +7,7 @@ printShortUsage()
 {
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
-    printf 'Usage: %q %s\n' "$(basename "$1")" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--emulate-prompt] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]]] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [-- [ARGUMENT [...]] [-?|-h|--help]'
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[--with-header|--with-prompt [--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--emulate-prompt]] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--worst-status] [--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]]] -c|--command "COMMANDLINE" [...] | SIMPLECOMMAND [...] [-- [ARGUMENT [...]] [-?|-h|--help]'
 }
 printUsage()
 {
@@ -30,17 +30,17 @@ HELPDESCRIPTION
     --with-header   Print a header (containing COMMAND) before each execution.
     --with-prompt   Emulate a full prompt (as if invoking COMMAND) before each
 		    execution.
-    --initial-status NUM    Customizations of the prompt emulation around
-    --trailing-prompt	    COMMAND; cp. runWithPrompt
+    --emulate-prompt	    Customizations of the prompt emulation around
+    --initial-status NUM    COMMAND; cp. runWithPrompt
+    --trailing-prompt
     --no-trailing-prompt
     --no-output-no-prompt
     --no-output-no-error
-    --no-success-no-count
-    --no-count-on N
+    --no-success-no-count   Stop on condition / summarize at end; cp. runWith
+    --no-count-on N	    Cannot be combined with --with-header.
     --exit-on-success
     --exit-on-failure
     --exit-on NUM
-    --emulate-prompt
     --worst-status
     --comment COMMENT
     --summarize-failed ERROR-TEXT
@@ -48,7 +48,7 @@ HELPDESCRIPTION
 
 EXIT STATUS:
 Overall exit status is the highest status of all. If you specify any
-runWithPrompt argument, --worst-status needs to be explicitly passed.
+runWith[Prompt] argument, --worst-status needs to be explicitly passed.
 
 Example:
 HELPTEXT
@@ -57,6 +57,7 @@ HELPTEXT
 
 with=
 typeset -a commands=()
+runWithCommand=runWith
 typeset -a runWithPromptArgs=()
 while [ $# -ne 0 ]
 do
@@ -64,7 +65,7 @@ do
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
 	--command|-c)	shift; commands+=("$1"); shift;;
 	--with-header)	shift; with=header;;
-	--with-prompt)	shift; with=prompt;;
+	--with-prompt)	shift; with=prompt; runWithCommand=runWithPrompt;;
 
 	--trailing-prompt|--no-trailing-prompt|--no-output-no-prompt|--no-output-no-error|--no-success-no-count|--exit-on-success|--exit-on-failure|--emulate-prompt|--worst-status)
 			runWithPromptArgs+=("$1"); shift;;
@@ -86,9 +87,16 @@ do
     esac
 done
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+elif [ ${#runWithPromptArgs[@]} -gt 0 -a "$with" = header ]; then
+    echo 'ERROR: Cannot combine runWith[Prompt] arguments with --with-header.'
+    echo
+    printUsage "$0"
+    exit 2
+fi >&2
 
 
 case "$with" in
@@ -104,7 +112,7 @@ case "$with" in
 		printf ' %q' "$@"
 		printf '\n'
 	    fi
-	done | runWithPrompt "${runWithPromptArgs[@]}"
+	done | ${runWithCommand:?} "${runWithPromptArgs[@]}"
 	;;
     *)
 	status=0
