ENH: Add special handling for no-op 99 status via --status-99-is-noop flag
So that COMMANDs exiting with 99 are treated as successful (if --worst-status is given as well), instead of 99 being used as the highest encountered exit status.

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release

diff --git a/bin/runWith b/bin/runWith
--- a/bin/runWith
+++ b/bin/runWith
@@ -2,7 +2,7 @@
 
 printShortUsage()
 {
-    printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--emulate-prompt] [--worst-status] [-c|--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [-?|-h|--help]'
+    printf 'Usage: echo COMMANDLINES | %q %s\n' "$(basename "$1")" '[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM] [--emulate-prompt] [--worst-status [--status-99-is-noop]] [-c|--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]] [-?|-h|--help]'
     echo
     printf 'Usage: %q %s <<EOF\n  COMMANDS\nEOF\n' "$(basename "$1")" '[...]'
 }
@@ -42,6 +42,8 @@ HELPDESCRIPTION
     --exit-unless NUM	Stop execution if COMMAND does not exit with NUM.
     --worst-status	Return the highest exit status of all COMMANDS instead
 			of the exit status of the last COMMAND.
+    --status-99-is-noop An exit status of 99 from COMMAND signifies no action or
+			inapplicability, and is treated like success.
     --comment|-c COMMENT
 			Use COMMENT instead of the default counter of executed
 			COMMANDS.
@@ -70,6 +72,7 @@ noCountOn=
 exitOn=
 exitComparison=-eq
 isWorstStatus=
+additionalSuccessStatus=
 isSummarizeFailed=
 summarizeFailedSeparator=' '
 summarizeFailedPrefix=
@@ -90,6 +93,7 @@ do
 	--exit-unless)		shift; exitOn="$1"; shift; exitComparison=-ne;;
 	--emulate-prompt)	shift;;
 	--worst-status)		shift; isWorstStatus=t;;
+	--status-99-is-noop)	shift; additionalSuccessStatus=99;;
 	--comment|-c)		shift; COMMENT="$1"; shift;;
 	--summarize-failed)	shift; isSummarizeFailed=t; summarizeFailedPrefix="$1"; shift;;
 	--summarize-failed-separator)	shift; summarizeFailedSeparator="$1"; shift;;
@@ -101,7 +105,7 @@ done
 [ $# -gt 0 ] && { printUsage "$0" >&2; exit 2; }
 
 count=
-overallExitStatus=0
+overallExitStatus=
 summarizeFailures=
 
 # Prevent that read command(s) consume following commands by reading from stdin.
@@ -125,18 +129,19 @@ do
 
     eval "$command"
     exitStatus=$?
-    [ "$isSkipCounting" ] || [ -n "$isNoSuccessNoCount" -a $exitStatus -ne 0 ] || [ "$noCountOn" = "$exitStatus" ] \
+    [ "$isSkipCounting" ] || [ -n "$isNoSuccessNoCount" -a $exitStatus -ne 0 -a $exitStatus -ne ${additionalSuccessStatus:-0} ] || [ ${noCountOn:--1} = $exitStatus ] \
 	|| let count+=1
     [ $exitStatus -eq 0 -o -z "$isSummarizeFailed" ] \
 	|| summarizeFailures+="${summarizeFailures:+$summarizeFailedSeparator}${COMMENT-$count}"
-    if [ ! "$isWorstStatus" -o $exitStatus -gt $overallExitStatus ]; then
+    if [ ! "$isWorstStatus" ] || [ $exitStatus -gt ${overallExitStatus:--1} -a $exitStatus -ne ${additionalSuccessStatus:--1} ]; then
 	overallExitStatus=$exitStatus
     fi
 
+    [ $exitStatus -eq ${additionalSuccessStatus:--1} ] && exitStatus=0	# Treat 99 as success for the --exit-on comparison.
     if [ "$exitOn" ] && [ $exitStatus $exitComparison $exitOn ]; then
 	break
     fi
 done
 [ "$summarizeFailures" ] && printf >&2 '%s%s\n' "$summarizeFailedPrefix" "$summarizeFailures"
 
-exit $overallExitStatus
+exit ${overallExitStatus:-${additionalSuccessStatus:-0}}
diff --git a/bin/runWithPrompt b/bin/runWithPrompt
--- a/bin/runWithPrompt
+++ b/bin/runWithPrompt
@@ -6,14 +6,14 @@ addAliasSupport()
     printf 'addAliasSupport %q %q %q %q %q\n' \
 	"$1" \
 	"${2}" \
-	"${3}${3:+|}with-header|with-prompt|trailing-prompt|no-trailing-prompt|no-output-no-prompt|no-output-no-error|emulate-prompt|no-success-no-count|exit-on-success|exit-on-failure|worst-status" \
+	"${3}${3:+|}with-header|with-prompt|trailing-prompt|no-trailing-prompt|no-output-no-prompt|no-output-no-error|emulate-prompt|no-success-no-count|exit-on-success|exit-on-failure|worst-status|status-99-is-noop" \
 	"${4}" \
 	"${5}${5:+|}initial-status|no-count-on|exit-on|exit-unless|comment|summarize-failed|summarize-failed-separator|between-command|usage-redirect"
 }
 
 getShortUsage()
 {
-    printf %s '[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM|--exit-unless NUM] [--emulate-prompt] [--worst-status] [-C|--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]]'
+    printf %s '[--initial-status NUM] [--trailing-prompt|--no-trailing-prompt] [--no-output-no-prompt] [--no-output-no-error] [--no-success-no-count|--no-count-on N] [--exit-on-success|--exit-on-failure|--exit-on NUM|--exit-unless NUM] [--emulate-prompt] [--worst-status [--status-99-is-noop]] [-C|--comment COMMENT] [--summarize-failed ERROR-TEXT [--summarize-failed-separator SEP]]'
 }
 printShortUsage()
 {
@@ -91,6 +91,8 @@ getLongUsage()
 			the rendering of PS1.
     --worst-status	Return the highest exit status of all COMMANDS instead
 			of the exit status of the last COMMAND.
+    --status-99-is-noop An exit status of 99 from COMMAND signifies no action or
+			inapplicability, and is treated like success.
     --comment|-C COMMENT
 			Use / replace \! in PS1 with COMMENT instead of the
 			default counter of executed COMMANDS.
@@ -127,6 +129,7 @@ noCountOn=
 exitOn=
 exitComparison=-eq
 isWorstStatus=
+additionalSuccessStatus=
 isSummarizeFailed=
 summarizeFailedSeparator=' '
 summarizeFailedPrefix=
@@ -151,6 +154,7 @@ do
 	--exit-unless)		shift; exitOn="$1"; shift; exitComparison=-ne;;
 	--emulate-prompt)	shift; isEmulatePrompt=t;;
 	--worst-status)		shift; isWorstStatus=t;;
+	--status-99-is-noop)	shift; additionalSuccessStatus=99;;
 	--comment|-C)		shift; COMMENT="$1"; shift;;
 	--summarize-failed)	shift; isSummarizeFailed=t; summarizeFailedPrefix="$1"; shift;;
 	--summarize-failed-separator)	shift; summarizeFailedSeparator="$1"; shift;;
@@ -296,14 +300,15 @@ commandWithPrompt()
 	local commandExitStatus=$?
 	exitStatus=$commandExitStatus
     fi
-    [ "$isSkipCounting" ] || [ -n "$isNoSuccessNoCount" -a $commandExitStatus -ne 0 ] || [ "$noCountOn" = "$commandExitStatus" ] \
+    [ "$isSkipCounting" ] || [ -n "$isNoSuccessNoCount" -a $commandExitStatus -ne 0 -a $commandExitStatus -ne ${additionalSuccessStatus:-0} ] || [ ${noCountOn:--1} -eq $commandExitStatus ] \
 	|| let count+=1
-    [ $exitStatus -eq 0 -o -z "$isSummarizeFailed" ] \
+    [ $exitStatus -eq 0 -o $exitStatus -eq ${additionalSuccessStatus:-0} -o -z "$isSummarizeFailed" ] \
 	|| summarizeFailures+="${summarizeFailures:+$summarizeFailedSeparator}${COMMENT-$count}"
-    if [ ! "$isWorstStatus" -o $exitStatus -gt $overallExitStatus ]; then
+    if [ ! "$isWorstStatus" ] || [ $exitStatus -gt ${overallExitStatus:--1} -a $exitStatus -ne ${additionalSuccessStatus:--1} ]; then
 	overallExitStatus=$exitStatus
     fi
 
+    [ $commandExitStatus -eq ${additionalSuccessStatus:--1} ] && commandExitStatus=0	# Treat 99 as success for the --exit-on comparison.
     if [ "$exitOn" ] && [ $commandExitStatus $exitComparison $exitOn ]; then
 	return 1
     fi
@@ -334,7 +339,7 @@ commandsFromArgs()
 }
 
 count=
-overallExitStatus=0
+overallExitStatus=
 summarizeFailures=
 
 [ ${#commands[@]} -eq 0 ] \
@@ -350,4 +355,4 @@ else
     [ "$summarizeFailures" ] && printf >&5 '%s%s\n' "$summarizeFailedPrefix" "$summarizeFailures"
 fi
 
-exit $overallExitStatus
+exit ${overallExitStatus:-${additionalSuccessStatus:-0}}
