singleton: ENH: Support killing the current instance via --kill

diff --git a/bin/singleton b/bin/singleton
--- a/bin/singleton
+++ b/bin/singleton
@@ -15,6 +15,8 @@ printShortUsage()
     # Note: short followed by long option; if the user knows the short one, she can
     # skim the long one.
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet|-v|--verbose] [-b|--block [-t|--timeout T[SUFFIX]]] [-i|--id ID] -c|--command "COMMANDLINE" [-c ...] | [--] SIMPLECOMMAND [-?|-h|--help]'
+    echo
+    printf 'Usage: %q %s\n' "$(basename "$1")" '[-q|--quiet|-v|--verbose] --kill -i|--id ID|-c|--command "COMMANDLINE" [-c ...]|[--] SIMPLECOMMAND'
 }
 printUsage()
 {
@@ -35,6 +37,8 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
+    --kill	    Kill a currently running singleton with ID / running
+		    COMMAND.
     --id|-i ID	    Identifier for the running COMMAND. If omitted, will use
 		    COMMAND itself.
     --quiet|-q	    Suppresses the default message if command execution is
@@ -59,6 +63,7 @@ EXIT STATUS:
 HELPTEXT
 }
 
+isKill=
 isQuiet=
 isVerbose=
 isBlock=
@@ -72,6 +77,7 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--kill)		shift; isKill=t;;
 	--command|-c)	shift; commands+=(${commands:+;} "$1"); isNeedEval=t; shift;;
 	--quiet|-q)	shift; isQuiet=t;;
 	--verbose|-v)	shift; isVerbose=t;;
@@ -102,7 +108,19 @@ if [ $# -ne 0 ]; then
 	commands=("$@")
     fi
 fi
-if [ ${#commands[@]} -eq 0 ]; then
+if [ "$isKill" ]; then
+    if [ -n "$id" -a ${#commands[@]} -gt 0 ]; then
+	    echo 'ERROR: Just pass either -i|--id ID or COMMAND for killing, not both.'
+	    echo
+	    printShortUsage "$0"
+	    exit 2
+    elif [ "$isBlock" ]; then
+	echo 'ERROR: --block cannot be combined with --kill.'
+	echo
+	printShortUsage "$0"
+	exit 2
+    fi >&2
+elif [ ${#commands[@]} -eq 0 ]; then
 	echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
 	exit 2
 fi
@@ -193,6 +211,47 @@ tryExecute()
     fi
     marker --end-transaction "$$"
 }
+
+if [ "$isKill" ]; then
+    status=0
+    if [ ! "$isQuiet" ] || [ "$isVerbose" ]; then
+	marker --start-read-transaction "$$" || exit 3
+	owner="$(getOwner)"
+	lastRun="$(transactionMarker --time "$escapedId" --format '')"
+	timeDiff="$(transactionMarker --diff "$escapedId")"
+	marker --end-transaction "$$" || exit 3
+    else
+	owner="$(marker --transactional --query "$escapedId" --get-context)"
+    fi
+
+    if [ "${owner:-0}" = 0 ]; then
+	[ "$isQuiet" ] || printf >&2 'No instance of %s is currently running.\n' "$id"
+	exit 1
+    fi
+
+    if kill "$owner" 2>/dev/null; then
+	newOwner="$(marker --transactional --query "$escapedId" --get-context)"
+
+	if [ "${newOwner:-0}" = 0 ]; then
+	    [ "$isVerbose" ] && printf >&2 '%s has been killed after running under PID %d since %s (%s).\n' "$id" "$owner" "$lastRun" "$(relativeTimeDiff "$timeDiff")"
+	else
+	    [ "$isQuiet" ] || printf >&2 '%s has been running under PID %d since %s (%s) and could not be killed.\n' "$id" "$newOwner" "$lastRun" "$(relativeTimeDiff "$timeDiff")"
+	    status=1
+	fi
+    elif ps -p "$owner" >/dev/null 2>&1; then
+	[ "$isQuiet" ] || printf >&2 '%s has been running under PID %d since %s (%s) and could not be killed.\n' "$id" "$owner" "$lastRun" "$(relativeTimeDiff "$timeDiff")"
+	status=1
+    else
+	[ "$isVerbose" ] && printf >&2 '%s had been running under PID %d since %s (%s), but that process does not exist any longer.\n' "$id" "$owner" "$lastRun" "$(relativeTimeDiff "$timeDiff")"
+
+	marker --start-write-transaction "$$" || exit 3
+	currentOwner="$(getOwner)"
+	[ "$currentOwner" = "$owner" ] && transactionMarker --update "$escapedId" --context 0
+	marker --end-transaction "$$" || exit 3
+    fi
+
+    exit $status
+fi
 
 isFirst=t
 SECONDS=0
